project_name: eea-cli
before:
  hooks:
    - go mod download
builds:
  - id: "eea"
    main: ./cmd/eea/
    binary: eea
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0

  - id: "eear"
    main: ./cmd/eear/
    binary: eear
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'